all:
  children:
  lamp_servers:
    hosts:
      server1:
        ansible_host: server_ip1
      server2:
        ansible_host: server_ip2
      server3:
        ansible_host: server_ip3
      server4:
        ansible_host: server_ip4
