all:
    childeren:
         lamp_servers:
            anisble_host : server_ip
            anisble_host : server_ip
            anisble_host : server_ip
            anisble_host : server_ip
          
